#      /$$$$$$                /$$   /$$
#     /$$__  $$              |__/  | $$
#    | $$  \__/ /$$  /$$  /$$ /$$ /$$$$$$
#    |  $$$$$$ | $$ | $$ | $$| $$|_  $$_/
#     \____  $$| $$ | $$ | $$| $$  | $$
#     /$$  \ $$| $$ | $$ | $$| $$  | $$ /$$
#    |  $$$$$$/|  $$$$$/$$$$/| $$  |  $$$$/
#     \______/  \_____/\___/ |__/   \___/


mapping_file: "mapping.json"
format: "Swit-mapping-v2" # Format List        |
                             # Swit-mapping-v1 | The old mapping format does not support as many features as v2
                             # Swit-mapping-v2 | Current version
                             # Auto-detect        | Automatically detect the format of mapping.json

