#        __               ____
#       / /   ___  ____ _/ __/_  __
#      / /   / _ \/ __ `/ /_/ / / /
#     / /___/  __/ /_/ / __/ /_/ /
#    /_____/\___/\__,_/_/  \__, /
#                         /____/

thread_calculator:
  cpu_cores:
    calculation: "logical + physical"

  plugin_count:
    calculation: "len(plugins_list)"

  threads_allocation:
    if_plugins_more_than_cpu:
      plugin_per_thread: "math.ceil(plugin_count / cpu_cores)"
      total_threads: "cpu_cores"
    if_cpu_more_or_equal_plugins:
      plugin_per_thread: 1
      total_threads: "plugin_count"
